const Cachable = require("./Cache/Cachable");

/**
 * Generic User; either a {@link TwitchUser} or {@link DiscordUser}.
 */
class User extends Cachable {
    /**
     * The ID of the user, generated by Discord or Twitch respectively.
     * 
     * @type {number}
     */
    id;

    /**
     * The Identity that the user is a part of.
     * @type {?Identity}
     */
    identity;

    /**
     * Constructs a new User object
     * 
     * @param {number} id 
     * @param {?Identity} identity 
     */
    constructor(id, identity) {
        super();

        this.id = id;
        this.identity = identity;
    }
}

module.exports = User;